kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: YKPWU9Stcs1/UOnFn2CH2q4Zlcjb8Hl528U1XDBrQZk=
      - identity: {}
