kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:node:worker-1
subjects:
- kind: ServiceAccount
  name: system:node:worker-1
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:node
  apiGroup: rbac.authorization.k8s.io
----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:node:worker-0
subjects:
- kind: ServiceAccount
  name: system:node:worker-0
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:node
  apiGroup: rbac.authorization.k8s.io
